### ISSUE TITLE
lastest pocketmine

### ISSUE THREAD

**Issue by SuperAdam47** [aieuo/car#3]
[Server thread/CRITICAL]: ArgumentCountError: "Too few arguments to function pocketmine\network\mcpe\protocol\types\EntityLink::__construct(), 3 passed in C:\Users\aronf\Desktop\Güncel GTD\plugins\car-master\src\aieuo\car\cars\Car.php on line 56 and exactly 5 expected" (EXCEPTION) in "src/pocketmine/network/mcpe/protocol/types/EntityLink" at line 43

**Comment by aieuo** [comment]
Thank you for your report. I'll fix it.
